/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocumentSourceVariant2
 */
public class DocumentSourceVariant2Test {
    private final DocumentSourceVariant2 model = new DocumentSourceVariant2();

    /**
     * Model tests for DocumentSourceVariant2
     */
    @Test
    public void testDocumentSourceVariant2() {
        // TODO: test DocumentSourceVariant2
    }

    /**
     * Test the property 'externalUrl'
     */
    @Test
    public void externalUrlTest() {
        // TODO: test externalUrl
    }

}
