/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocumentSourceWithUploadAndZip
 */
public class DocumentSourceWithUploadAndZipTest {
    private final DocumentSourceWithUploadAndZip model = new DocumentSourceWithUploadAndZip();

    /**
     * Model tests for DocumentSourceWithUploadAndZip
     */
    @Test
    public void testDocumentSourceWithUploadAndZip() {
        // TODO: test DocumentSourceWithUploadAndZip
    }

    /**
     * Test the property 'uploadRequestId'
     */
    @Test
    public void uploadRequestIdTest() {
        // TODO: test uploadRequestId
    }

    /**
     * Test the property 'zipId'
     */
    @Test
    public void zipIdTest() {
        // TODO: test zipId
    }

    /**
     * Test the property 'documentName'
     */
    @Test
    public void documentNameTest() {
        // TODO: test documentName
    }

}
