/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DocumentSourceVariant1 model module.
 * @module c2m_api/model/DocumentSourceVariant1
 * @version 2.0.0
 */
class DocumentSourceVariant1 {
    /**
     * Constructs a new <code>DocumentSourceVariant1</code>.
     * OneOf variant for documentSourceIdentifier
     * @alias module:c2m_api/model/DocumentSourceVariant1
     * @param documentId {Number} 
     */
    constructor(documentId) { 
        
        DocumentSourceVariant1.initialize(this, documentId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentId) { 
        obj['documentId'] = documentId;
    }

    /**
     * Constructs a <code>DocumentSourceVariant1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/DocumentSourceVariant1} obj Optional instance to populate.
     * @return {module:c2m_api/model/DocumentSourceVariant1} The populated <code>DocumentSourceVariant1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentSourceVariant1();

            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DocumentSourceVariant1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DocumentSourceVariant1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DocumentSourceVariant1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DocumentSourceVariant1.RequiredProperties = ["documentId"];

/**
 * @member {Number} documentId
 */
DocumentSourceVariant1.prototype['documentId'] = undefined;






export default DocumentSourceVariant1;

