/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DocumentSourceVariant2 model module.
 * @module c2m_api/model/DocumentSourceVariant2
 * @version 2.0.0
 */
class DocumentSourceVariant2 {
    /**
     * Constructs a new <code>DocumentSourceVariant2</code>.
     * OneOf variant for documentSourceIdentifier
     * @alias module:c2m_api/model/DocumentSourceVariant2
     * @param externalUrl {String} 
     */
    constructor(externalUrl) { 
        
        DocumentSourceVariant2.initialize(this, externalUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, externalUrl) { 
        obj['externalUrl'] = externalUrl;
    }

    /**
     * Constructs a <code>DocumentSourceVariant2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/DocumentSourceVariant2} obj Optional instance to populate.
     * @return {module:c2m_api/model/DocumentSourceVariant2} The populated <code>DocumentSourceVariant2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentSourceVariant2();

            if (data.hasOwnProperty('externalUrl')) {
                obj['externalUrl'] = ApiClient.convertToType(data['externalUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DocumentSourceVariant2</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DocumentSourceVariant2</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DocumentSourceVariant2.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['externalUrl'] && !(typeof data['externalUrl'] === 'string' || data['externalUrl'] instanceof String)) {
            throw new Error("Expected the field `externalUrl` to be a primitive type in the JSON string but got " + data['externalUrl']);
        }

        return true;
    }


}

DocumentSourceVariant2.RequiredProperties = ["externalUrl"];

/**
 * @member {String} externalUrl
 */
DocumentSourceVariant2.prototype['externalUrl'] = undefined;






export default DocumentSourceVariant2;

