/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.DocumentSourceVariant2

class DocumentSourceVariant2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of DocumentSourceVariant2
        //val modelInstance = DocumentSourceVariant2()

        // to test the property `externalUrl`
        should("test externalUrl") {
            // uncomment below to test the property
            //modelInstance.externalUrl shouldBe ("TODO")
        }

    }
}
