/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.DocumentSourceFromZip
import com.c2m.api.models.DocumentSourceVariant1
import com.c2m.api.models.DocumentSourceVariant2
import com.c2m.api.models.DocumentSourceWithUpload
import com.c2m.api.models.DocumentSourceWithUploadAndZip

class DocumentSourceIdentifierTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DocumentSourceIdentifier
        //val modelInstance = DocumentSourceIdentifier()

        // to test the property `documentId`
        should("test documentId") {
            // uncomment below to test the property
            //modelInstance.documentId shouldBe ("TODO")
        }

        // to test the property `externalUrl`
        should("test externalUrl") {
            // uncomment below to test the property
            //modelInstance.externalUrl shouldBe ("TODO")
        }

        // to test the property `uploadRequestId`
        should("test uploadRequestId") {
            // uncomment below to test the property
            //modelInstance.uploadRequestId shouldBe ("TODO")
        }

        // to test the property `documentName`
        should("test documentName") {
            // uncomment below to test the property
            //modelInstance.documentName shouldBe ("TODO")
        }

        // to test the property `zipId`
        should("test zipId") {
            // uncomment below to test the property
            //modelInstance.zipId shouldBe ("TODO")
        }

    }
}
