/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.SubmitSingleDocWithTemplateParams
import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.PaymentDetails
import com.c2m.api.models.RecipientAddressSource
import com.c2m.api.models.SubmitSingleDocWithTemplateParamsRequestOneOf
import com.c2m.api.models.SubmitSingleDocWithTemplateParamsRequestOneOf1
import com.c2m.api.models.SubmitSingleDocWithTemplateParamsRequestOneOf2

class SubmitSingleDocWithTemplateParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubmitSingleDocWithTemplateParams
        //val modelInstance = SubmitSingleDocWithTemplateParams()

        // to test the property `jobTemplate`
        should("test jobTemplate") {
            // uncomment below to test the property
            //modelInstance.jobTemplate shouldBe ("TODO")
        }

        // to test the property `documentSourceIdentifier`
        should("test documentSourceIdentifier") {
            // uncomment below to test the property
            //modelInstance.documentSourceIdentifier shouldBe ("TODO")
        }

        // to test the property `recipientAddressSources`
        should("test recipientAddressSources") {
            // uncomment below to test the property
            //modelInstance.recipientAddressSources shouldBe ("TODO")
        }

        // to test the property `paymentDetails`
        should("test paymentDetails") {
            // uncomment below to test the property
            //modelInstance.paymentDetails shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
