//
// DocumentSourceVariant1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OneOf variant for documentSourceIdentifier */
public struct DocumentSourceVariant1: Codable, JSONEncodable, Hashable {

    public var documentId: Int

    public init(documentId: Int) {
        self.documentId = documentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case documentId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(documentId, forKey: .documentId)
    }
}

