//
// DocumentSourceVariant2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OneOf variant for documentSourceIdentifier */
public struct DocumentSourceVariant2: Codable, JSONEncodable, Hashable {

    public var externalUrl: String

    public init(externalUrl: String) {
        self.externalUrl = externalUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(externalUrl, forKey: .externalUrl)
    }
}

