//
// MultiPdfWithCaptureParamsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MultiPdfWithCaptureParamsRequest: Codable, JSONEncodable, Hashable {

    public var addressCapturePdfs: [AddressListPdf]
    public var paymentDetails: PaymentDetails
    public var tags: [String]?

    public init(addressCapturePdfs: [AddressListPdf], paymentDetails: PaymentDetails, tags: [String]? = nil) {
        self.addressCapturePdfs = addressCapturePdfs
        self.paymentDetails = paymentDetails
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressCapturePdfs
        case paymentDetails
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addressCapturePdfs, forKey: .addressCapturePdfs)
        try container.encode(paymentDetails, forKey: .paymentDetails)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

