//
// RecipientAddressSourceOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RecipientAddressSourceOneOf1: Codable, JSONEncodable, Hashable {

    public var addressId: Int

    public init(addressId: Int) {
        self.addressId = addressId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addressId, forKey: .addressId)
    }
}

