//
// SubmitSingleDocWithTemplateParamsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SubmitSingleDocWithTemplateParamsRequest: Codable, JSONEncodable, Hashable {
    case typeSubmitSingleDocWithTemplateParamsRequestOneOf(SubmitSingleDocWithTemplateParamsRequestOneOf)
    case typeSubmitSingleDocWithTemplateParamsRequestOneOf1(SubmitSingleDocWithTemplateParamsRequestOneOf1)
    case typeSubmitSingleDocWithTemplateParamsRequestOneOf2(SubmitSingleDocWithTemplateParamsRequestOneOf2)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSubmitSingleDocWithTemplateParamsRequestOneOf(let value):
            try container.encode(value)
        case .typeSubmitSingleDocWithTemplateParamsRequestOneOf1(let value):
            try container.encode(value)
        case .typeSubmitSingleDocWithTemplateParamsRequestOneOf2(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SubmitSingleDocWithTemplateParamsRequestOneOf.self) {
            self = .typeSubmitSingleDocWithTemplateParamsRequestOneOf(value)
        } else if let value = try? container.decode(SubmitSingleDocWithTemplateParamsRequestOneOf1.self) {
            self = .typeSubmitSingleDocWithTemplateParamsRequestOneOf1(value)
        } else if let value = try? container.decode(SubmitSingleDocWithTemplateParamsRequestOneOf2.self) {
            self = .typeSubmitSingleDocWithTemplateParamsRequestOneOf2(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of SubmitSingleDocWithTemplateParamsRequest"))
        }
    }
}

