//
// SubmitSingleDocWithTemplateParamsRequestOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubmitSingleDocWithTemplateParamsRequestOneOf: Codable, JSONEncodable, Hashable {

    public var jobTemplate: String
    public var paymentDetails: PaymentDetails
    public var tags: [String]?
    public var recipientAddressSources: [RecipientAddressSource]

    public init(jobTemplate: String, paymentDetails: PaymentDetails, tags: [String]? = nil, recipientAddressSources: [RecipientAddressSource]) {
        self.jobTemplate = jobTemplate
        self.paymentDetails = paymentDetails
        self.tags = tags
        self.recipientAddressSources = recipientAddressSources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobTemplate
        case paymentDetails
        case tags
        case recipientAddressSources
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobTemplate, forKey: .jobTemplate)
        try container.encode(paymentDetails, forKey: .paymentDetails)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encode(recipientAddressSources, forKey: .recipientAddressSources)
    }
}

