/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.DocumentSourceIdentifier;
import com.c2m.model.PaymentDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * SubmitSingleDocWithTemplateParamsRequestOneOf1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-18T23:30:59.692465979Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class SubmitSingleDocWithTemplateParamsRequestOneOf1 {
  public static final String SERIALIZED_NAME_JOB_TEMPLATE = "jobTemplate";
  @SerializedName(SERIALIZED_NAME_JOB_TEMPLATE)
  @javax.annotation.Nonnull
  private String jobTemplate;

  public static final String SERIALIZED_NAME_PAYMENT_DETAILS = "paymentDetails";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DETAILS)
  @javax.annotation.Nonnull
  private PaymentDetails paymentDetails;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_DOCUMENT_SOURCE_IDENTIFIER = "documentSourceIdentifier";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_SOURCE_IDENTIFIER)
  @javax.annotation.Nonnull
  private DocumentSourceIdentifier documentSourceIdentifier;

  public SubmitSingleDocWithTemplateParamsRequestOneOf1() {
  }

  public SubmitSingleDocWithTemplateParamsRequestOneOf1 jobTemplate(@javax.annotation.Nonnull String jobTemplate) {
    this.jobTemplate = jobTemplate;
    return this;
  }

  /**
   * Get jobTemplate
   * @return jobTemplate
   */
  @javax.annotation.Nonnull
  public String getJobTemplate() {
    return jobTemplate;
  }

  public void setJobTemplate(@javax.annotation.Nonnull String jobTemplate) {
    this.jobTemplate = jobTemplate;
  }


  public SubmitSingleDocWithTemplateParamsRequestOneOf1 paymentDetails(@javax.annotation.Nonnull PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
    return this;
  }

  /**
   * Get paymentDetails
   * @return paymentDetails
   */
  @javax.annotation.Nonnull
  public PaymentDetails getPaymentDetails() {
    return paymentDetails;
  }

  public void setPaymentDetails(@javax.annotation.Nonnull PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
  }


  public SubmitSingleDocWithTemplateParamsRequestOneOf1 tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public SubmitSingleDocWithTemplateParamsRequestOneOf1 addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public SubmitSingleDocWithTemplateParamsRequestOneOf1 documentSourceIdentifier(@javax.annotation.Nonnull DocumentSourceIdentifier documentSourceIdentifier) {
    this.documentSourceIdentifier = documentSourceIdentifier;
    return this;
  }

  /**
   * Get documentSourceIdentifier
   * @return documentSourceIdentifier
   */
  @javax.annotation.Nonnull
  public DocumentSourceIdentifier getDocumentSourceIdentifier() {
    return documentSourceIdentifier;
  }

  public void setDocumentSourceIdentifier(@javax.annotation.Nonnull DocumentSourceIdentifier documentSourceIdentifier) {
    this.documentSourceIdentifier = documentSourceIdentifier;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitSingleDocWithTemplateParamsRequestOneOf1 submitSingleDocWithTemplateParamsRequestOneOf1 = (SubmitSingleDocWithTemplateParamsRequestOneOf1) o;
    return Objects.equals(this.jobTemplate, submitSingleDocWithTemplateParamsRequestOneOf1.jobTemplate) &&
        Objects.equals(this.paymentDetails, submitSingleDocWithTemplateParamsRequestOneOf1.paymentDetails) &&
        Objects.equals(this.tags, submitSingleDocWithTemplateParamsRequestOneOf1.tags) &&
        Objects.equals(this.documentSourceIdentifier, submitSingleDocWithTemplateParamsRequestOneOf1.documentSourceIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobTemplate, paymentDetails, tags, documentSourceIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitSingleDocWithTemplateParamsRequestOneOf1 {\n");
    sb.append("    jobTemplate: ").append(toIndentedString(jobTemplate)).append("\n");
    sb.append("    paymentDetails: ").append(toIndentedString(paymentDetails)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    documentSourceIdentifier: ").append(toIndentedString(documentSourceIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("jobTemplate", "paymentDetails", "tags", "documentSourceIdentifier"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("jobTemplate", "paymentDetails", "documentSourceIdentifier"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubmitSingleDocWithTemplateParamsRequestOneOf1
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubmitSingleDocWithTemplateParamsRequestOneOf1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubmitSingleDocWithTemplateParamsRequestOneOf1 is not found in the empty JSON string", SubmitSingleDocWithTemplateParamsRequestOneOf1.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubmitSingleDocWithTemplateParamsRequestOneOf1.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubmitSingleDocWithTemplateParamsRequestOneOf1` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubmitSingleDocWithTemplateParamsRequestOneOf1.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("jobTemplate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jobTemplate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jobTemplate").toString()));
      }
      // validate the required field `paymentDetails`
      PaymentDetails.validateJsonElement(jsonObj.get("paymentDetails"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      // validate the required field `documentSourceIdentifier`
      DocumentSourceIdentifier.validateJsonElement(jsonObj.get("documentSourceIdentifier"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmitSingleDocWithTemplateParamsRequestOneOf1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmitSingleDocWithTemplateParamsRequestOneOf1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmitSingleDocWithTemplateParamsRequestOneOf1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmitSingleDocWithTemplateParamsRequestOneOf1.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmitSingleDocWithTemplateParamsRequestOneOf1>() {
           @Override
           public void write(JsonWriter out, SubmitSingleDocWithTemplateParamsRequestOneOf1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmitSingleDocWithTemplateParamsRequestOneOf1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubmitSingleDocWithTemplateParamsRequestOneOf1 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubmitSingleDocWithTemplateParamsRequestOneOf1
   * @throws IOException if the JSON string is invalid with respect to SubmitSingleDocWithTemplateParamsRequestOneOf1
   */
  public static SubmitSingleDocWithTemplateParamsRequestOneOf1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmitSingleDocWithTemplateParamsRequestOneOf1.class);
  }

  /**
   * Convert an instance of SubmitSingleDocWithTemplateParamsRequestOneOf1 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

