/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.DocumentSourceFromZip
import com.c2m.api.models.DocumentSourceVariant1
import com.c2m.api.models.DocumentSourceVariant2
import com.c2m.api.models.DocumentSourceWithUpload
import com.c2m.api.models.DocumentSourceWithUploadAndZip

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param documentId 
 * @param externalUrl 
 * @param uploadRequestId 
 * @param documentName 
 * @param zipId 
 */


data class DocumentSourceIdentifier (

    @Json(name = "documentId")
    val documentId: kotlin.Int,

    @Json(name = "externalUrl")
    val externalUrl: java.net.URI,

    @Json(name = "uploadRequestId")
    val uploadRequestId: kotlin.Int,

    @Json(name = "documentName")
    val documentName: kotlin.String,

    @Json(name = "zipId")
    val zipId: kotlin.Int

) {


}

