/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * OneOf variant for documentSourceIdentifier
 *
 * @param externalUrl 
 */


data class DocumentSourceVariant2 (

    @Json(name = "externalUrl")
    val externalUrl: java.net.URI

) {


}

