/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.PaymentDetails

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param documentsToMerge 
 * @param jobTemplate 
 * @param paymentDetails 
 * @param tags 
 */


data class MergeMultiDocWithTemplateParams (

    @Json(name = "documentsToMerge")
    val documentsToMerge: kotlin.collections.List<DocumentSourceIdentifier>,

    @Json(name = "jobTemplate")
    val jobTemplate: kotlin.String,

    @Json(name = "paymentDetails")
    val paymentDetails: PaymentDetails,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

