/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.DocumentSourceIdentifier
import com.c2m.api.models.PaymentDetails
import com.c2m.api.models.RecipientAddressSource
import com.c2m.api.models.SubmitSingleDocWithTemplateParamsRequestOneOf
import com.c2m.api.models.SubmitSingleDocWithTemplateParamsRequestOneOf1
import com.c2m.api.models.SubmitSingleDocWithTemplateParamsRequestOneOf2

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param jobTemplate 
 * @param documentSourceIdentifier 
 * @param recipientAddressSources 
 * @param paymentDetails 
 * @param tags 
 */


data class SubmitSingleDocWithTemplateParamsRequest (

    @Json(name = "jobTemplate")
    val jobTemplate: kotlin.String,

    @Json(name = "documentSourceIdentifier")
    val documentSourceIdentifier: DocumentSourceIdentifier,

    @Json(name = "recipientAddressSources")
    val recipientAddressSources: kotlin.collections.List<RecipientAddressSource>,

    @Json(name = "paymentDetails")
    val paymentDetails: PaymentDetails? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

