# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from c2m_api.models.document_source_from_zip import DocumentSourceFromZip
from c2m_api.models.document_source_variant1 import DocumentSourceVariant1
from c2m_api.models.document_source_variant2 import DocumentSourceVariant2
from c2m_api.models.document_source_with_upload import DocumentSourceWithUpload
from c2m_api.models.document_source_with_upload_and_zip import DocumentSourceWithUploadAndZip
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DOCUMENTSOURCEIDENTIFIER_ONE_OF_SCHEMAS = ["DocumentSourceFromZip", "DocumentSourceVariant1", "DocumentSourceVariant2", "DocumentSourceWithUpload", "DocumentSourceWithUploadAndZip"]

class DocumentSourceIdentifier(BaseModel):
    """
    DocumentSourceIdentifier
    """
    # data type: DocumentSourceVariant1
    oneof_schema_1_validator: Optional[DocumentSourceVariant1] = None
    # data type: DocumentSourceVariant2
    oneof_schema_2_validator: Optional[DocumentSourceVariant2] = None
    # data type: DocumentSourceWithUpload
    oneof_schema_3_validator: Optional[DocumentSourceWithUpload] = None
    # data type: DocumentSourceWithUploadAndZip
    oneof_schema_4_validator: Optional[DocumentSourceWithUploadAndZip] = None
    # data type: DocumentSourceFromZip
    oneof_schema_5_validator: Optional[DocumentSourceFromZip] = None
    actual_instance: Optional[Union[DocumentSourceFromZip, DocumentSourceVariant1, DocumentSourceVariant2, DocumentSourceWithUpload, DocumentSourceWithUploadAndZip]] = None
    one_of_schemas: Set[str] = { "DocumentSourceFromZip", "DocumentSourceVariant1", "DocumentSourceVariant2", "DocumentSourceWithUpload", "DocumentSourceWithUploadAndZip" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DocumentSourceIdentifier.model_construct()
        error_messages = []
        match = 0
        # validate data type: DocumentSourceVariant1
        if not isinstance(v, DocumentSourceVariant1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocumentSourceVariant1`")
        else:
            match += 1
        # validate data type: DocumentSourceVariant2
        if not isinstance(v, DocumentSourceVariant2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocumentSourceVariant2`")
        else:
            match += 1
        # validate data type: DocumentSourceWithUpload
        if not isinstance(v, DocumentSourceWithUpload):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocumentSourceWithUpload`")
        else:
            match += 1
        # validate data type: DocumentSourceWithUploadAndZip
        if not isinstance(v, DocumentSourceWithUploadAndZip):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocumentSourceWithUploadAndZip`")
        else:
            match += 1
        # validate data type: DocumentSourceFromZip
        if not isinstance(v, DocumentSourceFromZip):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DocumentSourceFromZip`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DocumentSourceIdentifier with oneOf schemas: DocumentSourceFromZip, DocumentSourceVariant1, DocumentSourceVariant2, DocumentSourceWithUpload, DocumentSourceWithUploadAndZip. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DocumentSourceIdentifier with oneOf schemas: DocumentSourceFromZip, DocumentSourceVariant1, DocumentSourceVariant2, DocumentSourceWithUpload, DocumentSourceWithUploadAndZip. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DocumentSourceVariant1
        try:
            instance.actual_instance = DocumentSourceVariant1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DocumentSourceVariant2
        try:
            instance.actual_instance = DocumentSourceVariant2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DocumentSourceWithUpload
        try:
            instance.actual_instance = DocumentSourceWithUpload.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DocumentSourceWithUploadAndZip
        try:
            instance.actual_instance = DocumentSourceWithUploadAndZip.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DocumentSourceFromZip
        try:
            instance.actual_instance = DocumentSourceFromZip.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DocumentSourceIdentifier with oneOf schemas: DocumentSourceFromZip, DocumentSourceVariant1, DocumentSourceVariant2, DocumentSourceWithUpload, DocumentSourceWithUploadAndZip. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DocumentSourceIdentifier with oneOf schemas: DocumentSourceFromZip, DocumentSourceVariant1, DocumentSourceVariant2, DocumentSourceWithUpload, DocumentSourceWithUploadAndZip. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DocumentSourceFromZip, DocumentSourceVariant1, DocumentSourceVariant2, DocumentSourceWithUpload, DocumentSourceWithUploadAndZip]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


