// <auto-generated>
/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// SubmitSingleDocWithTemplateParamsRequestOneOf1
    /// </summary>
    public partial class SubmitSingleDocWithTemplateParamsRequestOneOf1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitSingleDocWithTemplateParamsRequestOneOf1" /> class.
        /// </summary>
        /// <param name="jobTemplate">jobTemplate</param>
        /// <param name="recipientAddressSources">recipientAddressSources</param>
        /// <param name="paymentDetails">paymentDetails</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public SubmitSingleDocWithTemplateParamsRequestOneOf1(string jobTemplate, List<RecipientAddressSource> recipientAddressSources, Option<PaymentDetails?> paymentDetails = default, Option<List<string>?> tags = default)
        {
            JobTemplate = jobTemplate;
            RecipientAddressSources = recipientAddressSources;
            PaymentDetailsOption = paymentDetails;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets JobTemplate
        /// </summary>
        [JsonPropertyName("jobTemplate")]
        public string JobTemplate { get; set; }

        /// <summary>
        /// Gets or Sets RecipientAddressSources
        /// </summary>
        [JsonPropertyName("recipientAddressSources")]
        public List<RecipientAddressSource> RecipientAddressSources { get; set; }

        /// <summary>
        /// Used to track the state of PaymentDetails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PaymentDetails?> PaymentDetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentDetails
        /// </summary>
        [JsonPropertyName("paymentDetails")]
        public PaymentDetails? PaymentDetails { get { return this.PaymentDetailsOption; } set { this.PaymentDetailsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string>? Tags { get { return this.TagsOption; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitSingleDocWithTemplateParamsRequestOneOf1 {\n");
            sb.Append("  JobTemplate: ").Append(JobTemplate).Append("\n");
            sb.Append("  RecipientAddressSources: ").Append(RecipientAddressSources).Append("\n");
            sb.Append("  PaymentDetails: ").Append(PaymentDetails).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SubmitSingleDocWithTemplateParamsRequestOneOf1" />
    /// </summary>
    public class SubmitSingleDocWithTemplateParamsRequestOneOf1JsonConverter : JsonConverter<SubmitSingleDocWithTemplateParamsRequestOneOf1>
    {
        /// <summary>
        /// Deserializes json to <see cref="SubmitSingleDocWithTemplateParamsRequestOneOf1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SubmitSingleDocWithTemplateParamsRequestOneOf1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> jobTemplate = default;
            Option<List<RecipientAddressSource>?> recipientAddressSources = default;
            Option<PaymentDetails?> paymentDetails = default;
            Option<List<string>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "jobTemplate":
                            jobTemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "recipientAddressSources":
                            recipientAddressSources = new Option<List<RecipientAddressSource>?>(JsonSerializer.Deserialize<List<RecipientAddressSource>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "paymentDetails":
                            paymentDetails = new Option<PaymentDetails?>(JsonSerializer.Deserialize<PaymentDetails>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!jobTemplate.IsSet)
                throw new ArgumentException("Property is required for class SubmitSingleDocWithTemplateParamsRequestOneOf1.", nameof(jobTemplate));

            if (!recipientAddressSources.IsSet)
                throw new ArgumentException("Property is required for class SubmitSingleDocWithTemplateParamsRequestOneOf1.", nameof(recipientAddressSources));

            if (jobTemplate.IsSet && jobTemplate.Value == null)
                throw new ArgumentNullException(nameof(jobTemplate), "Property is not nullable for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            if (recipientAddressSources.IsSet && recipientAddressSources.Value == null)
                throw new ArgumentNullException(nameof(recipientAddressSources), "Property is not nullable for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            if (paymentDetails.IsSet && paymentDetails.Value == null)
                throw new ArgumentNullException(nameof(paymentDetails), "Property is not nullable for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            return new SubmitSingleDocWithTemplateParamsRequestOneOf1(jobTemplate.Value!, recipientAddressSources.Value!, paymentDetails, tags);
        }

        /// <summary>
        /// Serializes a <see cref="SubmitSingleDocWithTemplateParamsRequestOneOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="submitSingleDocWithTemplateParamsRequestOneOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SubmitSingleDocWithTemplateParamsRequestOneOf1 submitSingleDocWithTemplateParamsRequestOneOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, submitSingleDocWithTemplateParamsRequestOneOf1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SubmitSingleDocWithTemplateParamsRequestOneOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="submitSingleDocWithTemplateParamsRequestOneOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SubmitSingleDocWithTemplateParamsRequestOneOf1 submitSingleDocWithTemplateParamsRequestOneOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (submitSingleDocWithTemplateParamsRequestOneOf1.JobTemplate == null)
                throw new ArgumentNullException(nameof(submitSingleDocWithTemplateParamsRequestOneOf1.JobTemplate), "Property is required for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            if (submitSingleDocWithTemplateParamsRequestOneOf1.RecipientAddressSources == null)
                throw new ArgumentNullException(nameof(submitSingleDocWithTemplateParamsRequestOneOf1.RecipientAddressSources), "Property is required for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            if (submitSingleDocWithTemplateParamsRequestOneOf1.PaymentDetailsOption.IsSet && submitSingleDocWithTemplateParamsRequestOneOf1.PaymentDetails == null)
                throw new ArgumentNullException(nameof(submitSingleDocWithTemplateParamsRequestOneOf1.PaymentDetails), "Property is required for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            if (submitSingleDocWithTemplateParamsRequestOneOf1.TagsOption.IsSet && submitSingleDocWithTemplateParamsRequestOneOf1.Tags == null)
                throw new ArgumentNullException(nameof(submitSingleDocWithTemplateParamsRequestOneOf1.Tags), "Property is required for class SubmitSingleDocWithTemplateParamsRequestOneOf1.");

            writer.WriteString("jobTemplate", submitSingleDocWithTemplateParamsRequestOneOf1.JobTemplate);

            writer.WritePropertyName("recipientAddressSources");
            JsonSerializer.Serialize(writer, submitSingleDocWithTemplateParamsRequestOneOf1.RecipientAddressSources, jsonSerializerOptions);
            if (submitSingleDocWithTemplateParamsRequestOneOf1.PaymentDetailsOption.IsSet)
            {
                writer.WritePropertyName("paymentDetails");
                JsonSerializer.Serialize(writer, submitSingleDocWithTemplateParamsRequestOneOf1.PaymentDetails, jsonSerializerOptions);
            }
            if (submitSingleDocWithTemplateParamsRequestOneOf1.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, submitSingleDocWithTemplateParamsRequestOneOf1.Tags, jsonSerializerOptions);
            }
        }
    }
}
