<?php
/**
 * DocumentSourceVariant2Test
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace C2MApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocumentSourceVariant2Test Class Doc Comment
 *
 * @category    Class
 * @description OneOf variant for documentSourceIdentifier
 * @package     C2MApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentSourceVariant2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocumentSourceVariant2"
     */
    public function testDocumentSourceVariant2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "external_url"
     */
    public function testPropertyExternalUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
