/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentSourceVariant2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentSourceVariant2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentSourceVariant2
        //private DocumentSourceVariant2 instance;

        public DocumentSourceVariant2Tests()
        {
            // TODO uncomment below to create an instance of DocumentSourceVariant2
            //instance = new DocumentSourceVariant2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentSourceVariant2
        /// </summary>
        [Fact]
        public void DocumentSourceVariant2InstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentSourceVariant2
            //Assert.IsType<DocumentSourceVariant2>(instance);
        }

        /// <summary>
        /// Test the property 'ExternalUrl'
        /// </summary>
        [Fact]
        public void ExternalUrlTest()
        {
            // TODO unit test for the property 'ExternalUrl'
        }
    }
}
