/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentSourceFromZip
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentSourceFromZipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentSourceFromZip
        //private DocumentSourceFromZip instance;

        public DocumentSourceFromZipTests()
        {
            // TODO uncomment below to create an instance of DocumentSourceFromZip
            //instance = new DocumentSourceFromZip();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentSourceFromZip
        /// </summary>
        [Fact]
        public void DocumentSourceFromZipInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentSourceFromZip
            //Assert.IsType<DocumentSourceFromZip>(instance);
        }

        /// <summary>
        /// Test the property 'ZipId'
        /// </summary>
        [Fact]
        public void ZipIdTest()
        {
            // TODO unit test for the property 'ZipId'
        }

        /// <summary>
        /// Test the property 'DocumentName'
        /// </summary>
        [Fact]
        public void DocumentNameTest()
        {
            // TODO unit test for the property 'DocumentName'
        }
    }
}
