/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentSourceWithUpload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentSourceWithUploadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentSourceWithUpload
        //private DocumentSourceWithUpload instance;

        public DocumentSourceWithUploadTests()
        {
            // TODO uncomment below to create an instance of DocumentSourceWithUpload
            //instance = new DocumentSourceWithUpload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentSourceWithUpload
        /// </summary>
        [Fact]
        public void DocumentSourceWithUploadInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentSourceWithUpload
            //Assert.IsType<DocumentSourceWithUpload>(instance);
        }

        /// <summary>
        /// Test the property 'UploadRequestId'
        /// </summary>
        [Fact]
        public void UploadRequestIdTest()
        {
            // TODO unit test for the property 'UploadRequestId'
        }

        /// <summary>
        /// Test the property 'DocumentName'
        /// </summary>
        [Fact]
        public void DocumentNameTest()
        {
            // TODO unit test for the property 'DocumentName'
        }
    }
}
