/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitSingleDocWithTemplateParamsRequestOneOf1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitSingleDocWithTemplateParamsRequestOneOf1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitSingleDocWithTemplateParamsRequestOneOf1
        //private SubmitSingleDocWithTemplateParamsRequestOneOf1 instance;

        public SubmitSingleDocWithTemplateParamsRequestOneOf1Tests()
        {
            // TODO uncomment below to create an instance of SubmitSingleDocWithTemplateParamsRequestOneOf1
            //instance = new SubmitSingleDocWithTemplateParamsRequestOneOf1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitSingleDocWithTemplateParamsRequestOneOf1
        /// </summary>
        [Fact]
        public void SubmitSingleDocWithTemplateParamsRequestOneOf1InstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitSingleDocWithTemplateParamsRequestOneOf1
            //Assert.IsType<SubmitSingleDocWithTemplateParamsRequestOneOf1>(instance);
        }

        /// <summary>
        /// Test the property 'JobTemplate'
        /// </summary>
        [Fact]
        public void JobTemplateTest()
        {
            // TODO unit test for the property 'JobTemplate'
        }

        /// <summary>
        /// Test the property 'PaymentDetails'
        /// </summary>
        [Fact]
        public void PaymentDetailsTest()
        {
            // TODO unit test for the property 'PaymentDetails'
        }

        /// <summary>
        /// Test the property 'RecipientAddressSources'
        /// </summary>
        [Fact]
        public void RecipientAddressSourcesTest()
        {
            // TODO unit test for the property 'RecipientAddressSources'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
