=begin
#C2M API v2 - Auth Overlay

#API for submitting documents with various routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::DocumentSourceWithUpload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::DocumentSourceWithUpload do
  let(:instance) { OpenapiClient::DocumentSourceWithUpload.new }

  describe 'test an instance of DocumentSourceWithUpload' do
    it 'should create an instance of DocumentSourceWithUpload' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::DocumentSourceWithUpload)
    end
  end

  describe 'test attribute "upload_request_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "document_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
