/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DocumentSourceIdentifier {
    DocumentSourceVariant1(Box<models::DocumentSourceVariant1>),
    DocumentSourceVariant2(Box<models::DocumentSourceVariant2>),
    DocumentSourceWithUpload(Box<models::DocumentSourceWithUpload>),
    DocumentSourceWithUploadAndZip(Box<models::DocumentSourceWithUploadAndZip>),
    DocumentSourceFromZip(Box<models::DocumentSourceFromZip>),
}

impl Default for DocumentSourceIdentifier {
    fn default() -> Self {
        Self::DocumentSourceVariant1(Default::default())
    }
}

