/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentSourceFromZip {
    #[serde(rename = "zipId")]
    pub zip_id: i32,
    #[serde(rename = "documentName")]
    pub document_name: String,
}

impl DocumentSourceFromZip {
    pub fn new(zip_id: i32, document_name: String) -> DocumentSourceFromZip {
        DocumentSourceFromZip {
            zip_id,
            document_name,
        }
    }
}

