/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DocumentSourceVariant2 : OneOf variant for documentSourceIdentifier
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentSourceVariant2 {
    #[serde(rename = "externalUrl")]
    pub external_url: String,
}

impl DocumentSourceVariant2 {
    /// OneOf variant for documentSourceIdentifier
    pub fn new(external_url: String) -> DocumentSourceVariant2 {
        DocumentSourceVariant2 {
            external_url,
        }
    }
}

