/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DocumentSourceVariant1 : OneOf variant for documentSourceIdentifier
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentSourceVariant1 {
    #[serde(rename = "documentId")]
    pub document_id: i32,
}

impl DocumentSourceVariant1 {
    /// OneOf variant for documentSourceIdentifier
    pub fn new(document_id: i32) -> DocumentSourceVariant1 {
        DocumentSourceVariant1 {
            document_id,
        }
    }
}

