/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiPdfWithCaptureParamsRequest {
    #[serde(rename = "addressCapturePdfs")]
    pub address_capture_pdfs: Vec<models::AddressListPdf>,
    #[serde(rename = "paymentDetails")]
    pub payment_details: Box<models::PaymentDetails>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl MultiPdfWithCaptureParamsRequest {
    pub fn new(address_capture_pdfs: Vec<models::AddressListPdf>, payment_details: models::PaymentDetails) -> MultiPdfWithCaptureParamsRequest {
        MultiPdfWithCaptureParamsRequest {
            address_capture_pdfs,
            payment_details: Box::new(payment_details),
            tags: None,
        }
    }
}

