/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipientAddressSourceOneOf1 {
    #[serde(rename = "addressId")]
    pub address_id: i32,
}

impl RecipientAddressSourceOneOf1 {
    pub fn new(address_id: i32) -> RecipientAddressSourceOneOf1 {
        RecipientAddressSourceOneOf1 {
            address_id,
        }
    }
}

