/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitSingleDocWithTemplateParamsRequestOneOf {
    #[serde(rename = "jobTemplate")]
    pub job_template: String,
    #[serde(rename = "paymentDetails")]
    pub payment_details: Box<models::PaymentDetails>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "recipientAddressSources")]
    pub recipient_address_sources: Vec<models::RecipientAddressSource>,
}

impl SubmitSingleDocWithTemplateParamsRequestOneOf {
    pub fn new(job_template: String, payment_details: models::PaymentDetails, recipient_address_sources: Vec<models::RecipientAddressSource>) -> SubmitSingleDocWithTemplateParamsRequestOneOf {
        SubmitSingleDocWithTemplateParamsRequestOneOf {
            job_template,
            payment_details: Box::new(payment_details),
            tags: None,
            recipient_address_sources,
        }
    }
}

