/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubmitSingleDocWithTemplateParamsRequest {
    SubmitSingleDocWithTemplateParamsRequestOneOf(Box<models::SubmitSingleDocWithTemplateParamsRequestOneOf>),
    SubmitSingleDocWithTemplateParamsRequestOneOf1(Box<models::SubmitSingleDocWithTemplateParamsRequestOneOf1>),
    SubmitSingleDocWithTemplateParamsRequestOneOf2(Box<models::SubmitSingleDocWithTemplateParamsRequestOneOf2>),
}

impl Default for SubmitSingleDocWithTemplateParamsRequest {
    fn default() -> Self {
        Self::SubmitSingleDocWithTemplateParamsRequestOneOf(Default::default())
    }
}

