/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentSourceWithUploadAndZip type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentSourceWithUploadAndZip{}

// DocumentSourceWithUploadAndZip struct for DocumentSourceWithUploadAndZip
type DocumentSourceWithUploadAndZip struct {
	UploadRequestId int32 `json:"uploadRequestId"`
	ZipId int32 `json:"zipId"`
	DocumentName string `json:"documentName"`
}

type _DocumentSourceWithUploadAndZip DocumentSourceWithUploadAndZip

// NewDocumentSourceWithUploadAndZip instantiates a new DocumentSourceWithUploadAndZip object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentSourceWithUploadAndZip(uploadRequestId int32, zipId int32, documentName string) *DocumentSourceWithUploadAndZip {
	this := DocumentSourceWithUploadAndZip{}
	this.UploadRequestId = uploadRequestId
	this.ZipId = zipId
	this.DocumentName = documentName
	return &this
}

// NewDocumentSourceWithUploadAndZipWithDefaults instantiates a new DocumentSourceWithUploadAndZip object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentSourceWithUploadAndZipWithDefaults() *DocumentSourceWithUploadAndZip {
	this := DocumentSourceWithUploadAndZip{}
	return &this
}

// GetUploadRequestId returns the UploadRequestId field value
func (o *DocumentSourceWithUploadAndZip) GetUploadRequestId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UploadRequestId
}

// GetUploadRequestIdOk returns a tuple with the UploadRequestId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceWithUploadAndZip) GetUploadRequestIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadRequestId, true
}

// SetUploadRequestId sets field value
func (o *DocumentSourceWithUploadAndZip) SetUploadRequestId(v int32) {
	o.UploadRequestId = v
}

// GetZipId returns the ZipId field value
func (o *DocumentSourceWithUploadAndZip) GetZipId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ZipId
}

// GetZipIdOk returns a tuple with the ZipId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceWithUploadAndZip) GetZipIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZipId, true
}

// SetZipId sets field value
func (o *DocumentSourceWithUploadAndZip) SetZipId(v int32) {
	o.ZipId = v
}

// GetDocumentName returns the DocumentName field value
func (o *DocumentSourceWithUploadAndZip) GetDocumentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentName
}

// GetDocumentNameOk returns a tuple with the DocumentName field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceWithUploadAndZip) GetDocumentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentName, true
}

// SetDocumentName sets field value
func (o *DocumentSourceWithUploadAndZip) SetDocumentName(v string) {
	o.DocumentName = v
}

func (o DocumentSourceWithUploadAndZip) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentSourceWithUploadAndZip) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uploadRequestId"] = o.UploadRequestId
	toSerialize["zipId"] = o.ZipId
	toSerialize["documentName"] = o.DocumentName
	return toSerialize, nil
}

func (o *DocumentSourceWithUploadAndZip) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uploadRequestId",
		"zipId",
		"documentName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentSourceWithUploadAndZip := _DocumentSourceWithUploadAndZip{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentSourceWithUploadAndZip)

	if err != nil {
		return err
	}

	*o = DocumentSourceWithUploadAndZip(varDocumentSourceWithUploadAndZip)

	return err
}

type NullableDocumentSourceWithUploadAndZip struct {
	value *DocumentSourceWithUploadAndZip
	isSet bool
}

func (v NullableDocumentSourceWithUploadAndZip) Get() *DocumentSourceWithUploadAndZip {
	return v.value
}

func (v *NullableDocumentSourceWithUploadAndZip) Set(val *DocumentSourceWithUploadAndZip) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentSourceWithUploadAndZip) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentSourceWithUploadAndZip) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentSourceWithUploadAndZip(val *DocumentSourceWithUploadAndZip) *NullableDocumentSourceWithUploadAndZip {
	return &NullableDocumentSourceWithUploadAndZip{value: val, isSet: true}
}

func (v NullableDocumentSourceWithUploadAndZip) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentSourceWithUploadAndZip) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


