/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentSourceWithUpload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentSourceWithUpload{}

// DocumentSourceWithUpload struct for DocumentSourceWithUpload
type DocumentSourceWithUpload struct {
	UploadRequestId int32 `json:"uploadRequestId"`
	DocumentName string `json:"documentName"`
}

type _DocumentSourceWithUpload DocumentSourceWithUpload

// NewDocumentSourceWithUpload instantiates a new DocumentSourceWithUpload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentSourceWithUpload(uploadRequestId int32, documentName string) *DocumentSourceWithUpload {
	this := DocumentSourceWithUpload{}
	this.UploadRequestId = uploadRequestId
	this.DocumentName = documentName
	return &this
}

// NewDocumentSourceWithUploadWithDefaults instantiates a new DocumentSourceWithUpload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentSourceWithUploadWithDefaults() *DocumentSourceWithUpload {
	this := DocumentSourceWithUpload{}
	return &this
}

// GetUploadRequestId returns the UploadRequestId field value
func (o *DocumentSourceWithUpload) GetUploadRequestId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UploadRequestId
}

// GetUploadRequestIdOk returns a tuple with the UploadRequestId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceWithUpload) GetUploadRequestIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadRequestId, true
}

// SetUploadRequestId sets field value
func (o *DocumentSourceWithUpload) SetUploadRequestId(v int32) {
	o.UploadRequestId = v
}

// GetDocumentName returns the DocumentName field value
func (o *DocumentSourceWithUpload) GetDocumentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentName
}

// GetDocumentNameOk returns a tuple with the DocumentName field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceWithUpload) GetDocumentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentName, true
}

// SetDocumentName sets field value
func (o *DocumentSourceWithUpload) SetDocumentName(v string) {
	o.DocumentName = v
}

func (o DocumentSourceWithUpload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentSourceWithUpload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uploadRequestId"] = o.UploadRequestId
	toSerialize["documentName"] = o.DocumentName
	return toSerialize, nil
}

func (o *DocumentSourceWithUpload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uploadRequestId",
		"documentName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentSourceWithUpload := _DocumentSourceWithUpload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentSourceWithUpload)

	if err != nil {
		return err
	}

	*o = DocumentSourceWithUpload(varDocumentSourceWithUpload)

	return err
}

type NullableDocumentSourceWithUpload struct {
	value *DocumentSourceWithUpload
	isSet bool
}

func (v NullableDocumentSourceWithUpload) Get() *DocumentSourceWithUpload {
	return v.value
}

func (v *NullableDocumentSourceWithUpload) Set(val *DocumentSourceWithUpload) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentSourceWithUpload) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentSourceWithUpload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentSourceWithUpload(val *DocumentSourceWithUpload) *NullableDocumentSourceWithUpload {
	return &NullableDocumentSourceWithUpload{value: val, isSet: true}
}

func (v NullableDocumentSourceWithUpload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentSourceWithUpload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


