/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubmitSingleDocWithTemplateParamsRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitSingleDocWithTemplateParamsRequestOneOf1{}

// SubmitSingleDocWithTemplateParamsRequestOneOf1 struct for SubmitSingleDocWithTemplateParamsRequestOneOf1
type SubmitSingleDocWithTemplateParamsRequestOneOf1 struct {
	JobTemplate string `json:"jobTemplate"`
	PaymentDetails PaymentDetails `json:"paymentDetails"`
	Tags []string `json:"tags,omitempty"`
	DocumentSourceIdentifier DocumentSourceIdentifier `json:"documentSourceIdentifier"`
}

type _SubmitSingleDocWithTemplateParamsRequestOneOf1 SubmitSingleDocWithTemplateParamsRequestOneOf1

// NewSubmitSingleDocWithTemplateParamsRequestOneOf1 instantiates a new SubmitSingleDocWithTemplateParamsRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitSingleDocWithTemplateParamsRequestOneOf1(jobTemplate string, paymentDetails PaymentDetails, documentSourceIdentifier DocumentSourceIdentifier) *SubmitSingleDocWithTemplateParamsRequestOneOf1 {
	this := SubmitSingleDocWithTemplateParamsRequestOneOf1{}
	this.JobTemplate = jobTemplate
	this.PaymentDetails = paymentDetails
	this.DocumentSourceIdentifier = documentSourceIdentifier
	return &this
}

// NewSubmitSingleDocWithTemplateParamsRequestOneOf1WithDefaults instantiates a new SubmitSingleDocWithTemplateParamsRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitSingleDocWithTemplateParamsRequestOneOf1WithDefaults() *SubmitSingleDocWithTemplateParamsRequestOneOf1 {
	this := SubmitSingleDocWithTemplateParamsRequestOneOf1{}
	return &this
}

// GetJobTemplate returns the JobTemplate field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetJobTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTemplate
}

// GetJobTemplateOk returns a tuple with the JobTemplate field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetJobTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTemplate, true
}

// SetJobTemplate sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) SetJobTemplate(v string) {
	o.JobTemplate = v
}

// GetPaymentDetails returns the PaymentDetails field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetPaymentDetails() PaymentDetails {
	if o == nil {
		var ret PaymentDetails
		return ret
	}

	return o.PaymentDetails
}

// GetPaymentDetailsOk returns a tuple with the PaymentDetails field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetPaymentDetailsOk() (*PaymentDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentDetails, true
}

// SetPaymentDetails sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) SetPaymentDetails(v PaymentDetails) {
	o.PaymentDetails = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) SetTags(v []string) {
	o.Tags = v
}

// GetDocumentSourceIdentifier returns the DocumentSourceIdentifier field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetDocumentSourceIdentifier() DocumentSourceIdentifier {
	if o == nil {
		var ret DocumentSourceIdentifier
		return ret
	}

	return o.DocumentSourceIdentifier
}

// GetDocumentSourceIdentifierOk returns a tuple with the DocumentSourceIdentifier field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) GetDocumentSourceIdentifierOk() (*DocumentSourceIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentSourceIdentifier, true
}

// SetDocumentSourceIdentifier sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) SetDocumentSourceIdentifier(v DocumentSourceIdentifier) {
	o.DocumentSourceIdentifier = v
}

func (o SubmitSingleDocWithTemplateParamsRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitSingleDocWithTemplateParamsRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobTemplate"] = o.JobTemplate
	toSerialize["paymentDetails"] = o.PaymentDetails
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["documentSourceIdentifier"] = o.DocumentSourceIdentifier
	return toSerialize, nil
}

func (o *SubmitSingleDocWithTemplateParamsRequestOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobTemplate",
		"paymentDetails",
		"documentSourceIdentifier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmitSingleDocWithTemplateParamsRequestOneOf1 := _SubmitSingleDocWithTemplateParamsRequestOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmitSingleDocWithTemplateParamsRequestOneOf1)

	if err != nil {
		return err
	}

	*o = SubmitSingleDocWithTemplateParamsRequestOneOf1(varSubmitSingleDocWithTemplateParamsRequestOneOf1)

	return err
}

type NullableSubmitSingleDocWithTemplateParamsRequestOneOf1 struct {
	value *SubmitSingleDocWithTemplateParamsRequestOneOf1
	isSet bool
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf1) Get() *SubmitSingleDocWithTemplateParamsRequestOneOf1 {
	return v.value
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf1) Set(val *SubmitSingleDocWithTemplateParamsRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSingleDocWithTemplateParamsRequestOneOf1(val *SubmitSingleDocWithTemplateParamsRequestOneOf1) *NullableSubmitSingleDocWithTemplateParamsRequestOneOf1 {
	return &NullableSubmitSingleDocWithTemplateParamsRequestOneOf1{value: val, isSet: true}
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


