/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubmitSingleDocWithTemplateParamsRequestOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitSingleDocWithTemplateParamsRequestOneOf2{}

// SubmitSingleDocWithTemplateParamsRequestOneOf2 struct for SubmitSingleDocWithTemplateParamsRequestOneOf2
type SubmitSingleDocWithTemplateParamsRequestOneOf2 struct {
	JobTemplate string `json:"jobTemplate"`
	PaymentDetails PaymentDetails `json:"paymentDetails"`
	Tags []string `json:"tags,omitempty"`
	DocumentSourceIdentifier DocumentSourceIdentifier `json:"documentSourceIdentifier"`
	RecipientAddressSources []RecipientAddressSource `json:"recipientAddressSources"`
}

type _SubmitSingleDocWithTemplateParamsRequestOneOf2 SubmitSingleDocWithTemplateParamsRequestOneOf2

// NewSubmitSingleDocWithTemplateParamsRequestOneOf2 instantiates a new SubmitSingleDocWithTemplateParamsRequestOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitSingleDocWithTemplateParamsRequestOneOf2(jobTemplate string, paymentDetails PaymentDetails, documentSourceIdentifier DocumentSourceIdentifier, recipientAddressSources []RecipientAddressSource) *SubmitSingleDocWithTemplateParamsRequestOneOf2 {
	this := SubmitSingleDocWithTemplateParamsRequestOneOf2{}
	this.JobTemplate = jobTemplate
	this.PaymentDetails = paymentDetails
	this.DocumentSourceIdentifier = documentSourceIdentifier
	this.RecipientAddressSources = recipientAddressSources
	return &this
}

// NewSubmitSingleDocWithTemplateParamsRequestOneOf2WithDefaults instantiates a new SubmitSingleDocWithTemplateParamsRequestOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitSingleDocWithTemplateParamsRequestOneOf2WithDefaults() *SubmitSingleDocWithTemplateParamsRequestOneOf2 {
	this := SubmitSingleDocWithTemplateParamsRequestOneOf2{}
	return &this
}

// GetJobTemplate returns the JobTemplate field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetJobTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTemplate
}

// GetJobTemplateOk returns a tuple with the JobTemplate field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetJobTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTemplate, true
}

// SetJobTemplate sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) SetJobTemplate(v string) {
	o.JobTemplate = v
}

// GetPaymentDetails returns the PaymentDetails field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetPaymentDetails() PaymentDetails {
	if o == nil {
		var ret PaymentDetails
		return ret
	}

	return o.PaymentDetails
}

// GetPaymentDetailsOk returns a tuple with the PaymentDetails field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetPaymentDetailsOk() (*PaymentDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentDetails, true
}

// SetPaymentDetails sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) SetPaymentDetails(v PaymentDetails) {
	o.PaymentDetails = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) SetTags(v []string) {
	o.Tags = v
}

// GetDocumentSourceIdentifier returns the DocumentSourceIdentifier field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetDocumentSourceIdentifier() DocumentSourceIdentifier {
	if o == nil {
		var ret DocumentSourceIdentifier
		return ret
	}

	return o.DocumentSourceIdentifier
}

// GetDocumentSourceIdentifierOk returns a tuple with the DocumentSourceIdentifier field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetDocumentSourceIdentifierOk() (*DocumentSourceIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentSourceIdentifier, true
}

// SetDocumentSourceIdentifier sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) SetDocumentSourceIdentifier(v DocumentSourceIdentifier) {
	o.DocumentSourceIdentifier = v
}

// GetRecipientAddressSources returns the RecipientAddressSources field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetRecipientAddressSources() []RecipientAddressSource {
	if o == nil {
		var ret []RecipientAddressSource
		return ret
	}

	return o.RecipientAddressSources
}

// GetRecipientAddressSourcesOk returns a tuple with the RecipientAddressSources field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) GetRecipientAddressSourcesOk() ([]RecipientAddressSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecipientAddressSources, true
}

// SetRecipientAddressSources sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) SetRecipientAddressSources(v []RecipientAddressSource) {
	o.RecipientAddressSources = v
}

func (o SubmitSingleDocWithTemplateParamsRequestOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitSingleDocWithTemplateParamsRequestOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobTemplate"] = o.JobTemplate
	toSerialize["paymentDetails"] = o.PaymentDetails
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["documentSourceIdentifier"] = o.DocumentSourceIdentifier
	toSerialize["recipientAddressSources"] = o.RecipientAddressSources
	return toSerialize, nil
}

func (o *SubmitSingleDocWithTemplateParamsRequestOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobTemplate",
		"paymentDetails",
		"documentSourceIdentifier",
		"recipientAddressSources",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmitSingleDocWithTemplateParamsRequestOneOf2 := _SubmitSingleDocWithTemplateParamsRequestOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmitSingleDocWithTemplateParamsRequestOneOf2)

	if err != nil {
		return err
	}

	*o = SubmitSingleDocWithTemplateParamsRequestOneOf2(varSubmitSingleDocWithTemplateParamsRequestOneOf2)

	return err
}

type NullableSubmitSingleDocWithTemplateParamsRequestOneOf2 struct {
	value *SubmitSingleDocWithTemplateParamsRequestOneOf2
	isSet bool
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf2) Get() *SubmitSingleDocWithTemplateParamsRequestOneOf2 {
	return v.value
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf2) Set(val *SubmitSingleDocWithTemplateParamsRequestOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSingleDocWithTemplateParamsRequestOneOf2(val *SubmitSingleDocWithTemplateParamsRequestOneOf2) *NullableSubmitSingleDocWithTemplateParamsRequestOneOf2 {
	return &NullableSubmitSingleDocWithTemplateParamsRequestOneOf2{value: val, isSet: true}
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


