/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubmitSingleDocWithTemplateParamsRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitSingleDocWithTemplateParamsRequestOneOf{}

// SubmitSingleDocWithTemplateParamsRequestOneOf struct for SubmitSingleDocWithTemplateParamsRequestOneOf
type SubmitSingleDocWithTemplateParamsRequestOneOf struct {
	JobTemplate string `json:"jobTemplate"`
	PaymentDetails PaymentDetails `json:"paymentDetails"`
	Tags []string `json:"tags,omitempty"`
	RecipientAddressSources []RecipientAddressSource `json:"recipientAddressSources"`
}

type _SubmitSingleDocWithTemplateParamsRequestOneOf SubmitSingleDocWithTemplateParamsRequestOneOf

// NewSubmitSingleDocWithTemplateParamsRequestOneOf instantiates a new SubmitSingleDocWithTemplateParamsRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitSingleDocWithTemplateParamsRequestOneOf(jobTemplate string, paymentDetails PaymentDetails, recipientAddressSources []RecipientAddressSource) *SubmitSingleDocWithTemplateParamsRequestOneOf {
	this := SubmitSingleDocWithTemplateParamsRequestOneOf{}
	this.JobTemplate = jobTemplate
	this.PaymentDetails = paymentDetails
	this.RecipientAddressSources = recipientAddressSources
	return &this
}

// NewSubmitSingleDocWithTemplateParamsRequestOneOfWithDefaults instantiates a new SubmitSingleDocWithTemplateParamsRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitSingleDocWithTemplateParamsRequestOneOfWithDefaults() *SubmitSingleDocWithTemplateParamsRequestOneOf {
	this := SubmitSingleDocWithTemplateParamsRequestOneOf{}
	return &this
}

// GetJobTemplate returns the JobTemplate field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetJobTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTemplate
}

// GetJobTemplateOk returns a tuple with the JobTemplate field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetJobTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTemplate, true
}

// SetJobTemplate sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) SetJobTemplate(v string) {
	o.JobTemplate = v
}

// GetPaymentDetails returns the PaymentDetails field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetPaymentDetails() PaymentDetails {
	if o == nil {
		var ret PaymentDetails
		return ret
	}

	return o.PaymentDetails
}

// GetPaymentDetailsOk returns a tuple with the PaymentDetails field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetPaymentDetailsOk() (*PaymentDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentDetails, true
}

// SetPaymentDetails sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) SetPaymentDetails(v PaymentDetails) {
	o.PaymentDetails = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) SetTags(v []string) {
	o.Tags = v
}

// GetRecipientAddressSources returns the RecipientAddressSources field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetRecipientAddressSources() []RecipientAddressSource {
	if o == nil {
		var ret []RecipientAddressSource
		return ret
	}

	return o.RecipientAddressSources
}

// GetRecipientAddressSourcesOk returns a tuple with the RecipientAddressSources field value
// and a boolean to check if the value has been set.
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) GetRecipientAddressSourcesOk() ([]RecipientAddressSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecipientAddressSources, true
}

// SetRecipientAddressSources sets field value
func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) SetRecipientAddressSources(v []RecipientAddressSource) {
	o.RecipientAddressSources = v
}

func (o SubmitSingleDocWithTemplateParamsRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitSingleDocWithTemplateParamsRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobTemplate"] = o.JobTemplate
	toSerialize["paymentDetails"] = o.PaymentDetails
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["recipientAddressSources"] = o.RecipientAddressSources
	return toSerialize, nil
}

func (o *SubmitSingleDocWithTemplateParamsRequestOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobTemplate",
		"paymentDetails",
		"recipientAddressSources",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmitSingleDocWithTemplateParamsRequestOneOf := _SubmitSingleDocWithTemplateParamsRequestOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmitSingleDocWithTemplateParamsRequestOneOf)

	if err != nil {
		return err
	}

	*o = SubmitSingleDocWithTemplateParamsRequestOneOf(varSubmitSingleDocWithTemplateParamsRequestOneOf)

	return err
}

type NullableSubmitSingleDocWithTemplateParamsRequestOneOf struct {
	value *SubmitSingleDocWithTemplateParamsRequestOneOf
	isSet bool
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf) Get() *SubmitSingleDocWithTemplateParamsRequestOneOf {
	return v.value
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf) Set(val *SubmitSingleDocWithTemplateParamsRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSingleDocWithTemplateParamsRequestOneOf(val *SubmitSingleDocWithTemplateParamsRequestOneOf) *NullableSubmitSingleDocWithTemplateParamsRequestOneOf {
	return &NullableSubmitSingleDocWithTemplateParamsRequestOneOf{value: val, isSet: true}
}

func (v NullableSubmitSingleDocWithTemplateParamsRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


