/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// SubmitSingleDocWithTemplateParamsRequest - struct for SubmitSingleDocWithTemplateParamsRequest
type SubmitSingleDocWithTemplateParamsRequest struct {
	SubmitSingleDocWithTemplateParamsRequestOneOf *SubmitSingleDocWithTemplateParamsRequestOneOf
	SubmitSingleDocWithTemplateParamsRequestOneOf1 *SubmitSingleDocWithTemplateParamsRequestOneOf1
	SubmitSingleDocWithTemplateParamsRequestOneOf2 *SubmitSingleDocWithTemplateParamsRequestOneOf2
}

// SubmitSingleDocWithTemplateParamsRequestOneOfAsSubmitSingleDocWithTemplateParamsRequest is a convenience function that returns SubmitSingleDocWithTemplateParamsRequestOneOf wrapped in SubmitSingleDocWithTemplateParamsRequest
func SubmitSingleDocWithTemplateParamsRequestOneOfAsSubmitSingleDocWithTemplateParamsRequest(v *SubmitSingleDocWithTemplateParamsRequestOneOf) SubmitSingleDocWithTemplateParamsRequest {
	return SubmitSingleDocWithTemplateParamsRequest{
		SubmitSingleDocWithTemplateParamsRequestOneOf: v,
	}
}

// SubmitSingleDocWithTemplateParamsRequestOneOf1AsSubmitSingleDocWithTemplateParamsRequest is a convenience function that returns SubmitSingleDocWithTemplateParamsRequestOneOf1 wrapped in SubmitSingleDocWithTemplateParamsRequest
func SubmitSingleDocWithTemplateParamsRequestOneOf1AsSubmitSingleDocWithTemplateParamsRequest(v *SubmitSingleDocWithTemplateParamsRequestOneOf1) SubmitSingleDocWithTemplateParamsRequest {
	return SubmitSingleDocWithTemplateParamsRequest{
		SubmitSingleDocWithTemplateParamsRequestOneOf1: v,
	}
}

// SubmitSingleDocWithTemplateParamsRequestOneOf2AsSubmitSingleDocWithTemplateParamsRequest is a convenience function that returns SubmitSingleDocWithTemplateParamsRequestOneOf2 wrapped in SubmitSingleDocWithTemplateParamsRequest
func SubmitSingleDocWithTemplateParamsRequestOneOf2AsSubmitSingleDocWithTemplateParamsRequest(v *SubmitSingleDocWithTemplateParamsRequestOneOf2) SubmitSingleDocWithTemplateParamsRequest {
	return SubmitSingleDocWithTemplateParamsRequest{
		SubmitSingleDocWithTemplateParamsRequestOneOf2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SubmitSingleDocWithTemplateParamsRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SubmitSingleDocWithTemplateParamsRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.SubmitSingleDocWithTemplateParamsRequestOneOf)
	if err == nil {
		jsonSubmitSingleDocWithTemplateParamsRequestOneOf, _ := json.Marshal(dst.SubmitSingleDocWithTemplateParamsRequestOneOf)
		if string(jsonSubmitSingleDocWithTemplateParamsRequestOneOf) == "{}" { // empty struct
			dst.SubmitSingleDocWithTemplateParamsRequestOneOf = nil
		} else {
			if err = validator.Validate(dst.SubmitSingleDocWithTemplateParamsRequestOneOf); err != nil {
				dst.SubmitSingleDocWithTemplateParamsRequestOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.SubmitSingleDocWithTemplateParamsRequestOneOf = nil
	}

	// try to unmarshal data into SubmitSingleDocWithTemplateParamsRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.SubmitSingleDocWithTemplateParamsRequestOneOf1)
	if err == nil {
		jsonSubmitSingleDocWithTemplateParamsRequestOneOf1, _ := json.Marshal(dst.SubmitSingleDocWithTemplateParamsRequestOneOf1)
		if string(jsonSubmitSingleDocWithTemplateParamsRequestOneOf1) == "{}" { // empty struct
			dst.SubmitSingleDocWithTemplateParamsRequestOneOf1 = nil
		} else {
			if err = validator.Validate(dst.SubmitSingleDocWithTemplateParamsRequestOneOf1); err != nil {
				dst.SubmitSingleDocWithTemplateParamsRequestOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.SubmitSingleDocWithTemplateParamsRequestOneOf1 = nil
	}

	// try to unmarshal data into SubmitSingleDocWithTemplateParamsRequestOneOf2
	err = newStrictDecoder(data).Decode(&dst.SubmitSingleDocWithTemplateParamsRequestOneOf2)
	if err == nil {
		jsonSubmitSingleDocWithTemplateParamsRequestOneOf2, _ := json.Marshal(dst.SubmitSingleDocWithTemplateParamsRequestOneOf2)
		if string(jsonSubmitSingleDocWithTemplateParamsRequestOneOf2) == "{}" { // empty struct
			dst.SubmitSingleDocWithTemplateParamsRequestOneOf2 = nil
		} else {
			if err = validator.Validate(dst.SubmitSingleDocWithTemplateParamsRequestOneOf2); err != nil {
				dst.SubmitSingleDocWithTemplateParamsRequestOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.SubmitSingleDocWithTemplateParamsRequestOneOf2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SubmitSingleDocWithTemplateParamsRequestOneOf = nil
		dst.SubmitSingleDocWithTemplateParamsRequestOneOf1 = nil
		dst.SubmitSingleDocWithTemplateParamsRequestOneOf2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SubmitSingleDocWithTemplateParamsRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SubmitSingleDocWithTemplateParamsRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SubmitSingleDocWithTemplateParamsRequest) MarshalJSON() ([]byte, error) {
	if src.SubmitSingleDocWithTemplateParamsRequestOneOf != nil {
		return json.Marshal(&src.SubmitSingleDocWithTemplateParamsRequestOneOf)
	}

	if src.SubmitSingleDocWithTemplateParamsRequestOneOf1 != nil {
		return json.Marshal(&src.SubmitSingleDocWithTemplateParamsRequestOneOf1)
	}

	if src.SubmitSingleDocWithTemplateParamsRequestOneOf2 != nil {
		return json.Marshal(&src.SubmitSingleDocWithTemplateParamsRequestOneOf2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SubmitSingleDocWithTemplateParamsRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SubmitSingleDocWithTemplateParamsRequestOneOf != nil {
		return obj.SubmitSingleDocWithTemplateParamsRequestOneOf
	}

	if obj.SubmitSingleDocWithTemplateParamsRequestOneOf1 != nil {
		return obj.SubmitSingleDocWithTemplateParamsRequestOneOf1
	}

	if obj.SubmitSingleDocWithTemplateParamsRequestOneOf2 != nil {
		return obj.SubmitSingleDocWithTemplateParamsRequestOneOf2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SubmitSingleDocWithTemplateParamsRequest) GetActualInstanceValue() (interface{}) {
	if obj.SubmitSingleDocWithTemplateParamsRequestOneOf != nil {
		return *obj.SubmitSingleDocWithTemplateParamsRequestOneOf
	}

	if obj.SubmitSingleDocWithTemplateParamsRequestOneOf1 != nil {
		return *obj.SubmitSingleDocWithTemplateParamsRequestOneOf1
	}

	if obj.SubmitSingleDocWithTemplateParamsRequestOneOf2 != nil {
		return *obj.SubmitSingleDocWithTemplateParamsRequestOneOf2
	}

	// all schemas are nil
	return nil
}

type NullableSubmitSingleDocWithTemplateParamsRequest struct {
	value *SubmitSingleDocWithTemplateParamsRequest
	isSet bool
}

func (v NullableSubmitSingleDocWithTemplateParamsRequest) Get() *SubmitSingleDocWithTemplateParamsRequest {
	return v.value
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequest) Set(val *SubmitSingleDocWithTemplateParamsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSingleDocWithTemplateParamsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSingleDocWithTemplateParamsRequest(val *SubmitSingleDocWithTemplateParamsRequest) *NullableSubmitSingleDocWithTemplateParamsRequest {
	return &NullableSubmitSingleDocWithTemplateParamsRequest{value: val, isSet: true}
}

func (v NullableSubmitSingleDocWithTemplateParamsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSingleDocWithTemplateParamsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


