/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentSourceFromZip type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentSourceFromZip{}

// DocumentSourceFromZip struct for DocumentSourceFromZip
type DocumentSourceFromZip struct {
	ZipId int32 `json:"zipId"`
	DocumentName string `json:"documentName"`
}

type _DocumentSourceFromZip DocumentSourceFromZip

// NewDocumentSourceFromZip instantiates a new DocumentSourceFromZip object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentSourceFromZip(zipId int32, documentName string) *DocumentSourceFromZip {
	this := DocumentSourceFromZip{}
	this.ZipId = zipId
	this.DocumentName = documentName
	return &this
}

// NewDocumentSourceFromZipWithDefaults instantiates a new DocumentSourceFromZip object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentSourceFromZipWithDefaults() *DocumentSourceFromZip {
	this := DocumentSourceFromZip{}
	return &this
}

// GetZipId returns the ZipId field value
func (o *DocumentSourceFromZip) GetZipId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ZipId
}

// GetZipIdOk returns a tuple with the ZipId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceFromZip) GetZipIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZipId, true
}

// SetZipId sets field value
func (o *DocumentSourceFromZip) SetZipId(v int32) {
	o.ZipId = v
}

// GetDocumentName returns the DocumentName field value
func (o *DocumentSourceFromZip) GetDocumentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentName
}

// GetDocumentNameOk returns a tuple with the DocumentName field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceFromZip) GetDocumentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentName, true
}

// SetDocumentName sets field value
func (o *DocumentSourceFromZip) SetDocumentName(v string) {
	o.DocumentName = v
}

func (o DocumentSourceFromZip) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentSourceFromZip) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zipId"] = o.ZipId
	toSerialize["documentName"] = o.DocumentName
	return toSerialize, nil
}

func (o *DocumentSourceFromZip) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zipId",
		"documentName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentSourceFromZip := _DocumentSourceFromZip{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentSourceFromZip)

	if err != nil {
		return err
	}

	*o = DocumentSourceFromZip(varDocumentSourceFromZip)

	return err
}

type NullableDocumentSourceFromZip struct {
	value *DocumentSourceFromZip
	isSet bool
}

func (v NullableDocumentSourceFromZip) Get() *DocumentSourceFromZip {
	return v.value
}

func (v *NullableDocumentSourceFromZip) Set(val *DocumentSourceFromZip) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentSourceFromZip) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentSourceFromZip) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentSourceFromZip(val *DocumentSourceFromZip) *NullableDocumentSourceFromZip {
	return &NullableDocumentSourceFromZip{value: val, isSet: true}
}

func (v NullableDocumentSourceFromZip) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentSourceFromZip) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


