/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentSourceVariant1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentSourceVariant1{}

// DocumentSourceVariant1 OneOf variant for documentSourceIdentifier
type DocumentSourceVariant1 struct {
	DocumentId int32 `json:"documentId"`
}

type _DocumentSourceVariant1 DocumentSourceVariant1

// NewDocumentSourceVariant1 instantiates a new DocumentSourceVariant1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentSourceVariant1(documentId int32) *DocumentSourceVariant1 {
	this := DocumentSourceVariant1{}
	this.DocumentId = documentId
	return &this
}

// NewDocumentSourceVariant1WithDefaults instantiates a new DocumentSourceVariant1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentSourceVariant1WithDefaults() *DocumentSourceVariant1 {
	this := DocumentSourceVariant1{}
	return &this
}

// GetDocumentId returns the DocumentId field value
func (o *DocumentSourceVariant1) GetDocumentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value
// and a boolean to check if the value has been set.
func (o *DocumentSourceVariant1) GetDocumentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentId, true
}

// SetDocumentId sets field value
func (o *DocumentSourceVariant1) SetDocumentId(v int32) {
	o.DocumentId = v
}

func (o DocumentSourceVariant1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentSourceVariant1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["documentId"] = o.DocumentId
	return toSerialize, nil
}

func (o *DocumentSourceVariant1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"documentId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentSourceVariant1 := _DocumentSourceVariant1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentSourceVariant1)

	if err != nil {
		return err
	}

	*o = DocumentSourceVariant1(varDocumentSourceVariant1)

	return err
}

type NullableDocumentSourceVariant1 struct {
	value *DocumentSourceVariant1
	isSet bool
}

func (v NullableDocumentSourceVariant1) Get() *DocumentSourceVariant1 {
	return v.value
}

func (v *NullableDocumentSourceVariant1) Set(val *DocumentSourceVariant1) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentSourceVariant1) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentSourceVariant1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentSourceVariant1(val *DocumentSourceVariant1) *NullableDocumentSourceVariant1 {
	return &NullableDocumentSourceVariant1{value: val, isSet: true}
}

func (v NullableDocumentSourceVariant1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentSourceVariant1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


